#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Camel Quarkus CI ppc64le

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  LANG: en_US.UTF-8
  MAVEN_OPTS: -Xmx3000m
  CQ_MAVEN_ARGS: -V -ntp -e -Daether.connector.http.connectionMaxTtl=120
  TESTCONTAINERS_RYUK_DISABLED: true
  CHECKOUT_REF: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' && github.head_ref || '' }}

jobs:
  pre-build-checks:
    if: github.repository == 'apache/camel-quarkus'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: [x86_64, ppc64le]
    outputs:
      continue-build: ${{ steps.pre-build-checks.outputs.continue-build }}
      run-checks: ${{ steps.init.outputs.run-checks }}
    steps:
      - name: Initialize
        id: init
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]] && [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
            echo "run-checks=true" >> $GITHUB_OUTPUT
          else
            echo "run-checks=false" >> $GITHUB_OUTPUT
          fi
      - name: Set up JDK 17
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        if: steps.init.outputs.run-checks == 'true'
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        if: steps.init.outputs.run-checks == 'true'
        with:
          ref: ${{ env.CHECKOUT_REF }}
          fetch-depth: 0
      - name: Pre build checks
        id: pre-build-checks
        run: |
          if [[ "${{ steps.init.outputs.run-checks }}" == "true" ]]; then
            ./mvnw cq:sync-versions -N ${CQ_MAVEN_ARGS}
            ./mvnw clean install -pl poms/bom -am -Dcq.flatten-bom.format --fail-never ${CQ_MAVEN_ARGS}
            ./mvnw clean install -f poms/bom ${CQ_MAVEN_ARGS}
            ./mvnw clean validate -pl docs ${CQ_MAVEN_ARGS}

            if [[ -z "$(git status --porcelain)" ]]; then
              echo "continue-build=true" >> $GITHUB_OUTPUT
            else
              mkdir ./dependabot-pr
              echo ${{ github.head_ref }} > ./dependabot-pr/BRANCH_REF
              echo ${{ github.event.pull_request.head.sha }} > ./dependabot-pr/PR_HEAD_SHA
              echo "$GITHUB_REF" | awk -F / '{print $3}' >  ./dependabot-pr/PR_NUMBER
              git diff -p --binary > ./dependabot-pr/changes.patch

              echo "continue-build=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "continue-build=true" >> $GITHUB_OUTPUT
          fi
      - name: Upload dependabot changeset
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: steps.pre-build-checks.outputs.continue-build == 'false'
        with:
          name: dependabot-pr-changeset
          path: dependabot-pr/
          retention-days: 1
          
  initial-mvn-install:
      if: needs.pre-build-checks.outputs.continue-build == 'true'
      runs-on: ubuntu-latest
      needs: pre-build-checks
      outputs:
        matrix: ${{ steps.set-native-matrix.outputs.matrix }}
        examples-matrix: ${{ steps.set-examples-matrix.outputs.examples-matrix }}
        alternate-jvm-matrix: ${{ steps.set-alternate-jvm-matrix.outputs.alternate-jvm-matrix }}
      env:
        MAVEN_OPTS: -Xmx4600m
      steps:
        - name: Check free space on disk
          run: |
            df -h /
        - name: Set up JDK 17
          uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
          with:
            distribution: 'temurin'
            java-version: '17'
        - name: Build Camel
          if: github.ref == 'refs/heads/camel-main' || github.base_ref == 'camel-main'
          run: |
            cd ../
            git clone --depth 1 --branch main https://github.com/apache/camel.git \
              && cd camel \
              && echo "Current Camel commit:" $(git rev-parse HEAD) \
              && ./mvnw ${CQ_MAVEN_ARGS} clean install -Dquickly -T1C
        - name: Build Quarkus
          if: github.ref == 'refs/heads/quarkus-main' || github.base_ref == 'quarkus-main'
          run: |
            git clone --depth 1 --branch main https://github.com/quarkusio/quarkus.git \
              && cd quarkus \
              && echo "Current Quarkus commit:" $(git rev-parse HEAD) \
              && sed -i '/<module>integration-tests<\/module>/d' pom.xml \
              && ./mvnw ${CQ_MAVEN_ARGS} clean install -Dquickly -Prelocations -T1C
        - name: Checkout
          uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
          with:
            ref: ${{ env.CHECKOUT_REF }}
            fetch-depth: 0
        - name: Update extension metadata
          run: |
            ./mvnw -N cq:update-quarkus-metadata ${CQ_MAVEN_ARGS}
        - name: mvn clean install -DskipTests
          run: |
            eval ./mvnw ${CQ_MAVEN_ARGS} ${BRANCH_OPTIONS} clean install -DskipTests -Dquarkus.build.skip -Pformat
        - name: Sync Maven properties
          run: |
            ./mvnw cq:sync-versions ${CQ_MAVEN_ARGS} -N
        - name: Fail if there are uncommitted changes
          shell: bash
          run: |
            [[ -z $(git status --porcelain | grep -v antora.yml) ]] || { echo 'There are uncommitted changes'; git status; git diff; exit 1; }
        - name: Tar Maven Repo
          shell: bash
          run: |
            tar -czf ${{ runner.temp }}/maven-repo.tgz -C ~ .m2/repository
            ls -lh ${{ runner.temp }}/maven-repo.tgz
            df -h /
        - name: Persist Maven Repo
          uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
          with:
            name: maven-repo
            path: ${{ runner.temp }}/maven-repo.tgz
            retention-days: 1
        - name: Setup Alternate JVM Matrix
          id: set-alternate-jvm-matrix
          shell: bash
          run: |
            cd integration-tests
            mvn help:evaluate -Dexpression=project.modules -N -q -DforceStdout | sed -e 's/<[^>]*>//g' -e 's/^[[:space:]]*//' -e '/^$/d' > ${{ runner.temp }}/itest-modules.txt
            MODULE_COUNT=$(wc -l < ${{ runner.temp }}/itest-modules.txt)
            GROUP1_COUNT=$((MODULE_COUNT / 2))
            GROUP2_COUNT=$((MODULE_COUNT - GROUP1_COUNT))
            GROUP1_MODULES=$(head -n $GROUP1_COUNT ${{ runner.temp }}/itest-modules.txt | tr '\n' ',' | sed 's/,$//')
            GROUP2_MODULES=$(tail -n $GROUP2_COUNT ${{ runner.temp }}/itest-modules.txt | tr '\n' ',' | sed 's/,$//')
            echo "alternate-jvm-matrix={'include': [{'name': 'group-01', 'modules': '${GROUP1_MODULES}'},{'name': 'group-02', 'modules': '${GROUP2_MODULES}'}]}" >> $GITHUB_OUTPUT
        - name: Setup Examples Matrix
          id: set-examples-matrix
          run: |
            EXAMPLES_BRANCH="camel-quarkus-main"
            if [[ ${GITHUB_REF_NAME} =~ [0-9]+.[0-9]+.x ]]; then
                EXAMPLES_BRANCH=${GITHUB_REF_NAME}
            elif [[ ${GITHUB_BASE_REF} =~ [0-9]+.[0-9]+.x ]]; then
                EXAMPLES_BRANCH=${GITHUB_BASE_REF}
            fi
  
            sudo apt install groovy -y --no-install-recommends
            EXAMPLES_MATRIX=$(groovy -DEXAMPLES_BRANCH=${EXAMPLES_BRANCH} tooling/scripts/generate-examples-matrix.groovy)
            echo "examples-matrix=${EXAMPLES_MATRIX}" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: [x86_64, ppc64le]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Maven build (JVM mode)  
        run: |
          ./mvnw clean install -DskipTests=false

      - name: Run JVM tests  
        run: |
          ./mvnw test
